import { createRouter as createTanStackRouter } from "@tanstack/react-router"
import { routeTree } from "./routeTree.gen" // generated by the TanStack Router plugin on first run

export function createRouter() {
  return createTanStackRouter({ routeTree, scrollRestoration: true })
}

declare module "@tanstack/react-router" {
  interface Register { router: ReturnType<typeof createRouter> }
}
